### ISSUE TITLE
I can't install regressors with pip in my computer

### ISSUE THREAD

**Issue by xfry-lixuan** [nsh87/regressors#26]
When I install regressors with pip,it has some problems.my computer installed numpy and scipy. But this problem still arises

`(osgeo) C:\Users\Lenovo>pip install regressors
Collecting regressors
  Using cached regressors-0.0.3.tar.gz (24 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in regressors setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by nsh87** [comment]
hi @xfry-lixuan, you can install with current Python e.g. 3.10 with

```shell
pip install git+https://github.com/nsh87/regressors.git@3a39e6aeb09953ccaeabec346f2eef324b7fcab9
```

**Comment by xfry-lixuan** [comment]
Thanks for your reply,I have solved the problem------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nsh87/regressors"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月4日(星期三) 上午6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nsh87/regressors] I can't install regressors with pip in my computer (Issue #26)





 
hi @xfry-lixuan, you can install with current Python e.g. 3.10 with
 pip install ***@***.***

**Comment by lixuan-code** [comment]
Thanks for your reply,I have solved the problem.
